import json
import requests
from requests.auth import HTTPBasicAuth


# ---------------------------------------------------
# Configuration (EDIT THESE)
# ---------------------------------------------------
CONFLUENCE_BASE_URL = "https://saym-homelab.atlassian.net"
CONFLUENCE_EMAIL = "your-email@example.com"   # REQUIRED: your Atlassian Cloud email
CONFLUENCE_API_KEY = "xxxx"                   # REQUIRED: API Token from Atlassian


auth = HTTPBasicAuth(CONFLUENCE_EMAIL, CONFLUENCE_API_KEY)
headers = {"Content-Type": "application/json"}


# ---------------------------------------------------
# Test URL / API connectivity
# ---------------------------------------------------
def test_api():
    url = f"{CONFLUENCE_BASE_URL}/wiki/rest/api/space"
    r = requests.get(url, auth=auth)
    print("\n=== TEST API ===")
    if r.status_code == 200:
        print("✔ API connection successful")
    else:
        print("✖ API connection failed")
        print("Status:", r.status_code)
        print("Response:", r.text)


# ---------------------------------------------------
# Get a page by ID
# ---------------------------------------------------
def get_page(page_id):
    url = f"{CONFLUENCE_BASE_URL}/wiki/api/v2/pages/{page_id}"
    r = requests.get(url, auth=auth)
    return r.json()


# ---------------------------------------------------
# Get page content (storage format)
# ---------------------------------------------------
def get_page_content(page_id):
    url = f"{CONFLUENCE_BASE_URL}/wiki/api/v2/pages/{page_id}?body-format=storage"
    r = requests.get(url, auth=auth)
    data = r.json()

    # Return only the HTML content
    return data.get("body", {}).get("storage", {}).get("value", "")


# ---------------------------------------------------
# Create a new page
# ---------------------------------------------------
def create_page(space_id, title, html_content):
    url = f"{CONFLUENCE_BASE_URL}/wiki/api/v2/pages"

    payload = {
        "spaceId": space_id,
        "title": title,
        "body": {
            "storage": {
                "value": html_content,
                "representation": "storage"
            }
        }
    }

    r = requests.post(url, headers=headers, auth=auth, data=json.dumps(payload))
    return r.json()


# ---------------------------------------------------
# Update (edit) an existing page
# ---------------------------------------------------
def update_page(page_id, new_html):
    page = get_page(page_id)
    current_version = page["version"]["number"]

    url = f"{CONFLUENCE_BASE_URL}/wiki/api/v2/pages/{page_id}"

    payload = {
        "version": {"number": current_version + 1},
        "title": page["title"],  # Must include title when updating
        "body": {
            "storage": {
                "value": new_html,
                "representation": "storage"
            }
        }
    }

    r = requests.put(url, headers=headers, auth=auth, data=json.dumps(payload))
    return r.json()


# ---------------------------------------------------
# Get ALL pages (with pagination)
# ---------------------------------------------------
def get_all_pages(limit=50):
    url = f"{CONFLUENCE_BASE_URL}/wiki/api/v2/pages"
    params = {"limit": limit}
    all_pages = []

    while True:
        r = requests.get(url, auth=auth, params=params)
        data = r.json()

        results = data.get("results", [])
        all_pages.extend(results)

        next_cursor = data.get("next")
        if not next_cursor:
            break

        url = next_cursor  # Confluence returns full next URL

    return all_pages


# ---------------------------------------------------
# Create multiple dummy pages
# ---------------------------------------------------
def create_dummy_pages(space_id, count=5, prefix="Dummy Page"):
    created_pages = []

    for i in range(1, count + 1):
        title = f"{prefix} {i}"
        html_content = (
            f"<h1>{title}</h1>"
            f"<p>This is autogenerated dummy content for page {i}.</p>"
        )

        result = create_page(space_id, title, html_content)
        created_pages.append(result)

        print(f"✔ Created: {title}")

    return created_pages


# ---------------------------------------------------
# Example usage / CLI
# ---------------------------------------------------
if __name__ == "__main__":
    print("Testing Confluence API...")
    test_api()

    print("\n=== Fetching ALL pages ===")
    pages = get_all_pages()
    print(f"Total pages found: {len(pages)}")

    for p in pages:
        print("-", p.get("title"))

    # ---- Create dummy pages (UNCOMMENT TO USE) ----
    # print("\n=== Creating Dummy Pages ===")
    # create_dummy_pages(
    #     space_id="123456",     # Replace with your space ID (numeric)
    #     count=10,
    #     prefix="Auto Test Page"
    # )
