/**
 * Description Service
 * 
 * Generates and updates PR descriptions with AI-powered analysis
 */

import * as core from '@actions/core';
import { PullRequestService, PRInfo } from '../github/PullRequestService';
import { BaseProvider } from '../providers/BaseProvider';
import { VERSION } from '../version';

export interface CommitInfo {
  sha: string;
  message: string;
  author: string;
  date: string;
}

export interface DescriptionServiceOptions {
  prService: PullRequestService;
  aiProvider: BaseProvider;
  prNumber: number;
}

export class DescriptionService {
  private readonly prService: PullRequestService;
  private readonly aiProvider: BaseProvider;
  private readonly prNumber: number;

  constructor(options: DescriptionServiceOptions) {
    this.prService = options.prService;
    this.aiProvider = options.aiProvider;
    this.prNumber = options.prNumber;
  }

  /**
   * Generate and update PR description
   */
  async generateDescription(): Promise<void> {
    try {
      core.info('📝 Generating PR description...');

      // Get PR info
      const prInfo = await this.prService.getPullRequest(this.prNumber);
      
      // Get commits
      const commits = await this.prService.getCommits(this.prNumber);
      
      // Get file diffs
      const files = await this.prService.getFiles(this.prNumber);

      // Build description prompt
      const prompt = this.buildDescriptionPrompt(prInfo, commits, files);

      // Generate description using AI
      core.info('🤖 Requesting description from AI...');
      const response = await this.aiProvider.sendMessage([
        { role: 'user', content: prompt }
      ], { responseFormat: 'text' });

      // Format description with footer
      const formattedDescription = this.formatDescription(response.content);

      // Update PR description
      await this.prService.updatePullRequest(this.prNumber, {
        body: formattedDescription
      });

      core.info('✅ PR description updated successfully');
    } catch (error) {
      core.error(`Failed to generate description: ${error instanceof Error ? error.message : String(error)}`);
      throw error;
    }
  }

  /**
   * Build prompt for AI description generation
   */
  private buildDescriptionPrompt(
    prInfo: PRInfo, 
    commits: Array<CommitInfo>,
    files: Array<any>
  ): string {
    // Format commits section
    const commitsSection = commits.map((c, idx) => 
      `${idx + 1}. ${c.message} (${c.author})`
    ).join('\n');

    // Format files section
    const filesSection = files.map(f => 
      `- **${f.filename}** (${f.status}, +${f.additions}/-${f.deletions})`
    ).join('\n');

    return `You are an expert technical writer creating a comprehensive pull request description.

Pull Request Information:
- Title: ${prInfo.title}
- Author: ${prInfo.author}
- Branch: ${prInfo.headRef} → ${prInfo.baseRef}
- Changes: +${prInfo.additions}/-${prInfo.deletions} lines across ${prInfo.changedFiles} files

Current Description:
${prInfo.body || 'No description provided'}

Commits (${commits.length}):
${commitsSection}

Files Changed (${files.length}):
${filesSection}

Please create a well-structured, professional PR description that includes:

## 📋 Summary
A clear, concise overview of what this PR accomplishes (2-3 sentences).

## 🎯 Purpose
The main goal and motivation behind these changes.

## 🔧 Changes
Key changes made in this PR:
- List major changes as bullet points
- Be specific and technical where appropriate
- Group related changes together

## 📝 Commit Overview
Brief summary of the commit history and development approach.

## ⚠️ Breaking Changes
List any breaking changes, or state "None" if there are no breaking changes.

## 🧪 Testing
Describe what testing was done or should be done (if information is available from commits/changes).

## 📚 Additional Notes
Any other relevant information, dependencies, or considerations.

Keep the tone professional and technical. Focus on what was changed and why, not how to use it. Make it easy for reviewers to understand the scope and impact of the changes.`;
  }

  /**
   * Format the AI-generated description with footer
   */
  private formatDescription(content: string): string {
    // Remove any existing AI-generated footer to avoid duplication
    const cleanContent = content.replace(/---\s*\n_Generated by.*_$/s, '').trim();

    return `${cleanContent}

---

_Generated by Code Sentinel AI v${VERSION} (${this.aiProvider.getModel()})_`;
  }
}
